app:
    resource: "@AppBundle/Resources/config/routing.yml"
    prefix:   /

usuarios:
    resource: "@UsuariosBundle/Resources/config/routing.yml"
    prefix:   /usuarios

#vehiculos:
#    resource: "@VehiculosBundle/Resources/config/routing.yml"
#    prefix:   /vehiculos

theme:
    resource: "@ThemeBundle/Resources/config/routing.yml"
    prefix:   /

ubicacion:
    resource: "@UbicacionBundle/Resources/config/routing.yml"
    prefix:   /ubicacion
    
util:
    resource: "@UtilBundle/Resources/config/routing.yml"
    prefix:   /utils

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

fos_user_group:
    resource: "@FOSUserBundle/Resources/config/routing/group.xml"
    prefix: /grupos

