<?php

namespace AppBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ColegiadoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CalleRepository extends EntityRepository {

    public function getCalleByNombreCodigo($nombreOCodigo) {
        $qb = $this->createQueryBuilder('e');
        $qb
                ->orWhere("upper(e.nombre) like upper(:nombreCodigo)")
                ->orWhere("upper(e.codigo) like upper(:nombreCodigo)");

        $qb->setParameter('nombreCodigo', '%' . $nombreOCodigo . '%');

        return $qb->getQuery()->getResult();
    }

    public function getCallesFilter($parametros = null) {
        $qb = $this->createQueryBuilder('e');

        if (isset($parametros['nombre'])) {
            $qb->andWhere('e.nombre like :nombre')
                    ->setParameter('nombre', "%" . $parametros['nombre'] . "%");
        }
        if (isset($parametros['codigo'])) {
            $qb->andWhere('e.codigo = :codigo')
                    ->setParameter('codigo', $parametros['codigo']);
        }

        return $qb->getQuery()->getResult();
    }

}
