<?php

namespace AppBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ColegiadoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CalleRepository extends EntityRepository {

    public function getCalleByNombreCodigo($nombreOCodigo) {
        $qb = $this->createQueryBuilder('e');
        $qb
                ->orWhere("upper(e.nombre) like upper(:nombreCodigo)")
                ->orWhere("upper(e.codigo) like upper(:nombreCodigo)");

        $qb->setParameter('nombreCodigo', '%' . $nombreOCodigo . '%');

        return $qb->getQuery()->getResult();
    }

}
