<?php

namespace AppBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * SituacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SituacionRepository extends EntityRepository {

   

    public function getSituacionesFilter($parametros = null) {
        $qb = $this->createQueryBuilder('e');

        if (isset($parametros['descripcion'])) {
            $qb->andWhere('e.descripcion like :descripcion')
                    ->setParameter('descripcion', "%" . $parametros['descripcion'] . "%");
        }
        if (isset($parametros['codigo'])) {
            $qb->andWhere('e.codigo = :codigo')
                    ->setParameter('codigo', $parametros['codigo']);
        }

        return $qb->getQuery()->getResult();
    }

}
