facultad:
    path:     /
    defaults: { _controller: "AppBundle:Facultad:index" }

facultad_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Facultad:show" }

facultad_new:
    path:     /new
    defaults: { _controller: "AppBundle:Facultad:new" }

facultad_create:
    path:     /create
    defaults: { _controller: "AppBundle:Facultad:create" }
    methods:  POST

facultad_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Facultad:edit" }

facultad_update:
    path:     /{id}/update
    defaults: { _controller: "AppBundle:Facultad:update" }
    methods:  [POST, PUT]

facultad_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Facultad:delete" }
    methods:  [POST, DELETE]
