situacion:
    path:     /
    defaults: { _controller: "AppBundle:Situacion:index" }

situacion_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Situacion:show" }

situacion_new:
    path:     /new
    defaults: { _controller: "AppBundle:Situacion:new" }

situacion_create:
    path:     /create
    defaults: { _controller: "AppBundle:Situacion:create" }
    methods:  POST

situacion_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Situacion:edit" }

situacion_update:
    path:     /{id}/update
    defaults: { _controller: "AppBundle:Situacion:update" }
    methods:  [POST, PUT]

situacion_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Situacion:delete" }
    methods:  [POST, DELETE]
