app_tipo_documento_expediente:
    resource: "@AppBundle/Resources/config/routing/tipodocumentoexpediente.yml"
    prefix:   /tipo_documento_expediente

app_documento:
    resource: "@AppBundle/Resources/config/routing/documento.yml"
    prefix:   /documento

app_colegiado:
    resource: "@AppBundle/Resources/config/routing/colegiado.yml"
    prefix:   /colegiado

app_tipodocumento:
    resource: "@AppBundle/Resources/config/routing/tipodocumento.yml"
    prefix:   /tipo_documento

app_situacion:
    resource: "@AppBundle/Resources/config/routing/situacion.yml"
    prefix:   /situacion

app_calle:
    resource: "@AppBundle/Resources/config/routing/calle.yml"
    prefix:   /calle

app_expediente:
    resource: "@AppBundle/Resources/config/routing/expediente.yml"
    prefix:   /expediente

app_hoja:
    resource: "@AppBundle/Resources/config/routing/hoja.yml"
    prefix:   /hoja

AppBundle_circunscripcion:
    resource: "@AppBundle/Resources/config/routing/circunscripcion.yml"
    prefix:   /circunscripcion

app_facultad:
    resource: "@AppBundle/Resources/config/routing/facultad.yml"
    prefix:   /facultad

app_item_aplicativo:
    resource: "@AppBundle/Resources/config/routing/itemaplicativo.yml"
    prefix:   /item_aplicativo

app_aplicativo:
    resource: "@AppBundle/Resources/config/routing/aplicativo.yml"
    prefix:   /aplicativo

app_homepage:
    path:     /
    defaults: { _controller: AppBundle:Default:index }

app_pantalla_vacia:
    path: /app_pantalla_vacia
    defaults: { _controller: "AppBundle:Default:pantallaVacia" }

#app_bloquear_pantalla:
#    path: /{vehiculoId}/app_bloquear_pantalla/
#    defaults: { _controller: "AppBundle:Default:bloquearPantalla" }

app_desbloquear_pantalla:
    path: /app_desbloquear_pantalla
    defaults: { _controller: "AppBundle:Default:desbloquearPantalla" }

colegiados_ajax:
    resource: "@AppBundle/Resources/config/routing/ajax.yml"
    prefix:   /ajax