<?php

namespace UbicacionBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * LocalidadRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LocalidadRepository extends EntityRepository
{
    public function getByLike($string, $extraParam = null) {

        $em = $this->getEntityManager();

        $consulta = $em->createQuery('SELECT l
                                          FROM UbicacionBundle:Localidad l
                                          WHERE upper(l.descripcion) LIKE upper(:string)
                                     ');


        $consulta->setParameter('string', '%' . $string . '%');


        $return = $consulta->getArrayResult();

        return $return;
    }
    
    public function getLocalidadByNombre($nombre) {
        $qb = $this->createQueryBuilder('e');
        $qb
                ->Where("upper(e.descripcion) like upper(:nombre)");

        $qb->setParameter('nombre', '%' . $nombre . '%');

        return $qb->getQuery()->getResult();
    }
    
     public function getLocalidadesFilter($parametros = null) {
        $qb = $this->createQueryBuilder('e');

        if (isset($parametros['descripcion'])) {
            $qb->andWhere('e.descripcion like :descripcion')
                    ->setParameter('descripcion', "%" . $parametros['descripcion'] . "%");
        }
        if (isset($parametros['codigo'])) {
            $qb->andWhere('e.codigo = :codigo')
                    ->setParameter('codigo', $parametros['codigo']);
        }

        return $qb->getQuery()->getResult();
    }
}
