<?php

namespace UbicacionBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UbicacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UbicacionRepository extends EntityRepository {

    public function getDepartamentosFilter($parametros = null) {
        $qb = $this->createQueryBuilder('e');

        if (isset($parametros['descripcion'])) {
            $qb->andWhere('e.descripcion like :descripcion')
                    ->setParameter('descripcion', "%" . $parametros['descripcion'] . "%");
        }
        if (isset($parametros['codigo'])) {
            $qb->andWhere('e.codigo = :codigo')
                    ->setParameter('codigo', $parametros['codigo']);
        }

        return $qb->getQuery()->getResult();
    }

    public function getPaisesFilter($parametros = null) {
        $qb = $this->createQueryBuilder('e');

        if (isset($parametros['descripcion'])) {
            $qb->andWhere('e.descripcion like :descripcion')
                    ->setParameter('descripcion', "%" . $parametros['descripcion'] . "%");
        }
        if (isset($parametros['codigo'])) {
            $qb->andWhere('e.codigoPais = :codigo')
                    ->setParameter('codigo', $parametros['codigo']);
        }

        return $qb->getQuery()->getResult();
    }

    public function getProvinciasFilter($parametros = null) {
        $qb = $this->createQueryBuilder('e');

        if (isset($parametros['descripcion'])) {
            $qb->andWhere('e.descripcion like :descripcion')
                    ->setParameter('descripcion', "%" . $parametros['descripcion'] . "%");
        }
        if (isset($parametros['codigo'])) {
            $qb->andWhere('e.codigo = :codigo')
                    ->setParameter('codigo', $parametros['codigo']);
        }

        return $qb->getQuery()->getResult();
    }

}
